import streamlit as st

def Dashboard_General():
    st.markdown("DASHBOARDDD GENERAL")

    ##PRODUCCIÓN MENSAUAL ANUAL, COSTOS DE TRANSPORTE, PEDIDO CLIENTES, CANTIDAD POR CLIENTE, DIAS QUE PIDEN MÁS MENOS, PRODUCTO QUE PIDEN MÁS POR ZONA, DISTRITO, DONDE TENEMOS MAYOR CONTROL EN DISTRITOS, QUEJAS, PRINCIPALES QUEJAS